### ISSUE TITLE
"invalid_grant: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI"

### ISSUE THREAD

**Issue by febeling** [stormz/omniauth-base#1]
A change in Omniauth caused all providers to break, including this one. The error is `invalid_grant`.

The relevant ticket in Omniauth itself is intridea/omniauth-oauth2#81, including a [workaround](https://github.com/intridea/omniauth-oauth2/issues/81#issuecomment-151281907), pinning `omniauth-oauth2` to 1.3.1 version.

It seems to be a stricter implementation of the spec, which breaks backward compatibility. 

A fix in this provider is likely necessary to become compatible with version 1.4 of omniauth.

**Comment by francois2metz** [comment]
Thanks, will take a look

Le 28 octobre 2015 10:05:02 GMT+01:00, Florian Ebeling notifications@github.com a écrit :

> A change in Omniauth caused all providers to break, including this one.
> The error is `invalid_grant`.
> 
> The relevant ticket in Omniauth itself is intridea/omniauth-oauth2#81,
> including a
> [workaround](https://github.com/intridea/omniauth-oauth2/issues/81#issuecomment-151281907),
> pinning Omniauth to 1.3.1 version.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/stormz/omniauth-base/issues/1

## 

François

**Comment by francois2metz** [comment]
Thanks for the report :green_heart: :heart: :purple_heart:

**Comment by febeling** [comment]
@francois2metz well, awesome turnaround time. Much appreciated. Thank you! :sparkles: :sparkling_heart:
